print("안녕하세요! 이름이 어떻게 되시나요?")
name = input()
print("나이가 몇살인가요?")
age = input()
print("학교가 어디에요?")
school = input()
print("몇학년인가요?(1/2/3)")
grade = input()
print("좋아하는 취미가 뭐에요?")
hobby = input()
print("안녕하세요, " + name + "님! " + name + "님은 " + age + "살 " + school + " " + grade+ "학년이고, " + hobby + "를 좋아합니다.")
